league:
  num_teams: 10
  roster: {QB: 1, RB: 2, WR: 2, TE: 1, FLEX: 1, DST: 1, K: 1, BENCH: 7}
  season_weeks: 17
  playoff_weeks: [15, 16, 17]
teams:
- {name: Team 1, draft_slot: 1, is_me: false}
- {name: Team 2, draft_slot: 2, is_me: false}
- {name: My Team, draft_slot: 3, is_me: true}
- {name: Team 4, draft_slot: 4, is_me: false}
- {name: Team 5, draft_slot: 5, is_me: false}
- {name: Team 6, draft_slot: 6, is_me: false}
- {name: Team 7, draft_slot: 7, is_me: false}
- {name: Team 8, draft_slot: 8, is_me: false}
- {name: Team 9, draft_slot: 9, is_me: false}
- {name: Team 10, draft_slot: 10, is_me: false}
schedule:
  1:
  - [Team 1, Team 10]
  - [Team 2, Team 9]
  - [My Team, Team 8]
  - [Team 4, Team 7]
  - [Team 5, Team 6]
  2:
  - [Team 1, Team 9]
  - [Team 10, Team 8]
  - [Team 2, Team 7]
  - [My Team, Team 6]
  - [Team 4, Team 5]
  3:
  - [Team 1, Team 8]
  - [Team 9, Team 7]
  - [Team 10, Team 6]
  - [Team 2, Team 5]
  - [My Team, Team 4]
  4:
  - [Team 1, Team 7]
  - [Team 8, Team 6]
  - [Team 9, Team 5]
  - [Team 10, Team 4]
  - [Team 2, My Team]
  5:
  - [Team 1, Team 6]
  - [Team 7, Team 5]
  - [Team 8, Team 4]
  - [Team 9, My Team]
  - [Team 10, Team 2]
  6:
  - [Team 1, Team 5]
  - [Team 6, Team 4]
  - [Team 7, My Team]
  - [Team 8, Team 2]
  - [Team 9, Team 10]
  7:
  - [Team 1, Team 4]
  - [Team 5, My Team]
  - [Team 6, Team 2]
  - [Team 7, Team 10]
  - [Team 8, Team 9]
  8:
  - [Team 1, My Team]
  - [Team 4, Team 2]
  - [Team 5, Team 10]
  - [Team 6, Team 9]
  - [Team 7, Team 8]
  9:
  - [Team 1, Team 2]
  - [My Team, Team 10]
  - [Team 4, Team 9]
  - [Team 5, Team 8]
  - [Team 6, Team 7]
  10:
  - [Team 10, Team 1]
  - [Team 9, Team 2]
  - [Team 8, My Team]
  - [Team 7, Team 4]
  - [Team 6, Team 5]
  11:
  - [Team 9, Team 1]
  - [Team 8, Team 10]
  - [Team 7, Team 2]
  - [Team 6, My Team]
  - [Team 5, Team 4]
  12:
  - [Team 8, Team 1]
  - [Team 7, Team 9]
  - [Team 6, Team 10]
  - [Team 5, Team 2]
  - [Team 4, My Team]
  13:
  - [Team 7, Team 1]
  - [Team 6, Team 8]
  - [Team 5, Team 9]
  - [Team 4, Team 10]
  - [My Team, Team 2]
  14:
  - [Team 6, Team 1]
  - [Team 5, Team 7]
  - [Team 4, Team 8]
  - [My Team, Team 9]
  - [Team 2, Team 10]
  15:
  - [Team 5, Team 1]
  - [Team 4, Team 6]
  - [My Team, Team 7]
  - [Team 2, Team 8]
  - [Team 10, Team 9]
  16:
  - [Team 4, Team 1]
  - [My Team, Team 5]
  - [Team 2, Team 6]
  - [Team 10, Team 7]
  - [Team 9, Team 8]
  17:
  - [My Team, Team 1]
  - [Team 2, Team 4]
  - [Team 10, Team 5]
  - [Team 9, Team 6]
  - [Team 8, Team 7]
draft: {type: snake, rounds: 16}
