league:
  num_teams: 12
  roster: {QB: 1, RB: 2, WR: 2, TE: 1, FLEX: 1, DT: 1, DE: 1, LB: 1, CB: 1, S: 1, K: 1, P: 1, BENCH: 7}
  season_weeks: 13
  playoff_weeks: []
teams:
- {name: Mafia, draft_slot: 4, is_me: false}
- {name: Alizeh, draft_slot: 6, is_me: false}
- {name: Justin, draft_slot: 11, is_me: false}
- {name: Srajat, draft_slot: 3, is_me: false}
- {name: Josh, draft_slot: 10, is_me: false}
- {name: Tampa, draft_slot: 12, is_me: false}
- {name: Flint, draft_slot: 8, is_me: false}
- {name: Adrian, draft_slot: 2, is_me: false}
- {name: Ammar, draft_slot: 1, is_me: true}
- {name: Jonathin, draft_slot: 7, is_me: false}
- {name: Touchdown, draft_slot: 5, is_me: false}
- {name: He, draft_slot: 9, is_me: false}
schedule:
  1:
  - [Ammar, Josh]
  - [Mafia, He]
  - [Alizeh, Jonathin]
  - [Justin, Tampa]
  - [Srajat, Touchdown]
  - [Flint, Adrian]
  2:
  - [Ammar, Srajat]
  - [Mafia, Josh]
  - [Alizeh, Touchdown]
  - [Justin, Adrian]
  - [Tampa, Jonathin]
  - [Flint, He]
  3:
  - [Ammar, Alizeh]
  - [Mafia, Srajat]
  - [Justin, He]
  - [Josh, Flint]
  - [Tampa, Adrian]
  - [Jonathin, Touchdown]
  4:
  - [Ammar, Touchdown]
  - [Mafia, Alizeh]
  - [Justin, Josh]
  - [Srajat, Flint]
  - [Tampa, He]
  - [Adrian, Jonathin]
  5:
  - [Ammar, Jonathin]
  - [Mafia, Touchdown]
  - [Alizeh, Flint]
  - [Justin, Srajat]
  - [Josh, Tampa]
  - [Adrian, He]
  6:
  - [Ammar, Mafia]
  - [Alizeh, Justin]
  - [Srajat, Tampa]
  - [Josh, Adrian]
  - [Flint, Touchdown]
  - [Jonathin, He]
  7:
  - [Ammar, Flint]
  - [Mafia, Jonathin]
  - [Alizeh, Tampa]
  - [Justin, Touchdown]
  - [Srajat, Adrian]
  - [Josh, He]
  8:
  - [Ammar, Justin]
  - [Mafia, Flint]
  - [Alizeh, Adrian]
  - [Srajat, He]
  - [Josh, Jonathin]
  - [Tampa, Touchdown]
  9:
  - [Ammar, Tampa]
  - [Mafia, Justin]
  - [Alizeh, He]
  - [Srajat, Josh]
  - [Flint, Jonathin]
  - [Adrian, Touchdown]
  10:
  - [Ammar, Adrian]
  - [Mafia, Tampa]
  - [Alizeh, Josh]
  - [Justin, Flint]
  - [Srajat, Jonathin]
  - [Touchdown, He]
  11:
  - [Ammar, He]
  - [Mafia, Adrian]
  - [Alizeh, Srajat]
  - [Justin, Jonathin]
  - [Josh, Touchdown]
  - [Tampa, Flint]
  12:
  - [Ammar, Josh]
  - [Mafia, He]
  - [Alizeh, Jonathin]
  - [Justin, Tampa]
  - [Srajat, Touchdown]
  - [Flint, Adrian]
  13:
  - [Ammar, Srajat]
  - [Mafia, Josh]
  - [Alizeh, Touchdown]
  - [Justin, Adrian]
  - [Tampa, Jonathin]
  - [Flint, He]
draft: {type: snake, rounds: 21}
